export const h2ColorPalette = [
  { name: 'White',   hex: '#FDFEFF' },
  { name: 'Steel',   hex: '#535353' },
  { name: 'Red',     hex: '#BE2C2C' },
  { name: 'Orange',  hex: '#F57A1F' },
  { name: 'Gold',    hex: '#F5D22C' },
  { name: 'Olive',   hex: '#9FAC59' },
  { name: 'Green',   hex: '#21922F' },
  { name: 'Sage',    hex: '#235644' },
  { name: 'Cyan',    hex: '#16A0A0' },
  { name: 'Teal',    hex: '#36747A' },
  { name: 'Cobalt',  hex: '#416C8F' },
  { name: 'Blue',    hex: '#28459B' },
  { name: 'Violet',  hex: '#6A4EB6' },
  { name: 'Purple',  hex: '#75466D' },
  { name: 'Pink',    hex: '#FB9BC9' },
  { name: 'Crimson', hex: '#981244' },
  { name: 'Brown',   hex: '#664E3E' },
  { name: 'Tan',     hex: '#B19256' },
];

export const h3ColorPalette = [
  { name: 'Steel',    hex: '#6E6E6E' },
  { name: 'Silver',   hex: '#B2B1B2' },
  { name: 'White',    hex: '#C6C7C6' },
  { name: 'Red',      hex: '#A53D3C' },
  { name: 'Mauve',    hex: '#DE7373' },
  { name: 'Salmon',   hex: '#F18C8C' },
  { name: 'Orange',   hex: '#DE9500' },
  { name: 'Coral',    hex: '#FCB762' },
  { name: 'Peach',    hex: '#FFD1A5' },
  { name: 'Gold',     hex: '#D3B536' },
  { name: 'Yellow',   hex: '#EFCC37' },
  { name: 'Pale',     hex: '#FFDE83' },
  { name: 'Sage',     hex: '#637F21' },
  { name: 'Green',    hex: '#9AAF6B' },
  { name: 'Olive',    hex: '#D9F1A7' },
  { name: 'Teal',     hex: '#398389' },
  { name: 'Aqua',     hex: '#55C3C8' },
  { name: 'Cyan',     hex: '#9CEFEF' },
  { name: 'Blue',     hex: '#3C659C' },
  { name: 'Cobalt',   hex: '#6092DE' },
  { name: 'Sapphire', hex: '#A1BEF7' },
  { name: 'Violet',   hex: '#604899' },
  { name: 'Orchid',   hex: '#9C80E9' },
  { name: 'Lavender', hex: '#CEC2FF' },
  { name: 'Crimson',  hex: '#8F0052' },
  { name: 'Rubine',   hex: '#D6468E' },
  { name: 'Pink',     hex: '#FF95C2' },
  { name: 'Brown',    hex: '#5D421B' },
  { name: 'Tan',      hex: '#B59578' },
  { name: 'Khaki',    hex: '#E4C5AA' },
];

export const h3TeamColors = {
  'red':        '#A73B3B',
  'blue':       '#3D69A7',
  'green':      '#63801C',
  'orange':     '#DF9600',
  'purple':     '#60479B',
  'yellow':     '#D4B632',
  'brown':      '#5D4016',
  'pink':       '#FF96C3',
};

export const h3GameModeColors = {
  'white':        '#EEEEEE',
  'black':        '#3B3B3B',
  'zombieGreen':  '#B5B888',
};
